BF: github - cycle to the next credential when we fail to obtain organization
Without it we immediately might fail if there is a known token which
does not have necessary permissions.  Typically this would lead to just
a failure like

    github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'

now we will just go to the next credential while also providing an
informative log message on either we succeeded or not.  So the interaction
would look like

	$> datalad create-sibling-github --github-organization datalad-collection-1 testds
	[WARNING] Having authenticated using token, we failed (401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}) to access information about organization datalad-collection-1. We will try next authentication method (if any left available)
	[INFO   ] Successfully obtained information about organization datalad-collection-1 using UserPassword(name='github', url='https://github.com/login') credential
	.: github(-) [https://github.com/datalad-collection-1/testds.git (git)]
	'https://github.com/datalad-collection-1/testds.git' configured as sibling 'github' for <Dataset path=/tmp/testds>