BF(unicode): use assure_unicode while formatting an exception
Otherwise was getting

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_ro_operations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 353, in run
    result.addError(self, sys.exc_info())
  File "/usr/lib/python2.7/dist-packages/nose/proxy.py", line 128, in addError
    formatted = plugins.formatError(self.test, err)
  File "/usr/lib/python2.7/dist-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/lib/python2.7/dist-packages/nose/plugins/manager.py", line 141, in chain
    result = meth(*arg, **kw)
  File "/usr/lib/python2.7/dist-packages/nose/plugins/logcapture.py", line 237, in formatError
    return (ec, self.addCaptureToErr(ev, records), tb)
  File "/usr/lib/python2.7/dist-packages/nose/plugins/logcapture.py", line 244, in addCaptureToErr
    records + \
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 652, in safe_str
    return str(val)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/exceptions.py", line 34, in __str__
    to_str += "\n%s" % self.msg
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 159: ordinal not in range(128)

while running the test which was supposed to error out with

datalad.support.exceptions.CommandError: CommandError: command 'sudo -n chmod -R 47521 /home/yoh/.tmp/datalad_temp_tree_test_ro_operationsvxxkb4f6/clone' failed with exitcode 1
Failed to run 'sudo -n chmod -R 47521 /home/yoh/.tmp/datalad_temp_tree_test_ro_operationsvxxkb4f6/clone' under None. Exit code=1. out= err=chmod: invalid mode: ‘47521’
Try 'chmod --help' for more information.