ENH: add exception_traceback ("unlimited") to the status dict if exception is passed into get_status_dict
And for demonstration of utility - added to a single sample invocation within download_url.
One of the main use cases is to be able to troubleshoot failed travis runs, where
at most we see only the last location in the traceback due to exc_str being used.
Like

    'message': "'ConsoleLog' object has no attribute 'yesno' "
             '[__init__.py:__getattribute__:101]',

Due to all the generators for results status messages processing etc, there is no
idea about original stack which lead to the failure :

	  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
		self.test(*self.arg)
	  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 271, in _wrap_skip_ssh
		return func(*args, **kwargs)
	  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
		return t(*(arg + (filename,)), **kw)
	  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
		return t(*(arg + (filename,)), **kw)
	  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/distributed/tests/test_ria_basics.py", line 468, in _test_binary_data
		ds.download_url(url, path=file, message="Add DICOM file from github")
	  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
		return f(**kwargs)
	  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/interface/utils.py", line 494, in eval_func
		return return_func(generator_func)(*args, **kwargs)
	  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/interface/utils.py", line 482, in return_func
		results = list(results)
	  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/interface/utils.py", line 469, in generator_func
		msg="Command did not complete successfully")
	datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
	[{'action': 'download_url',
	  'message': "'ConsoleLog' object has no attribute 'yesno' "
				 '[__init__.py:__getattribute__:101]',
	  'path': '/tmp/datalad_temp__test_binary_datajhq0ejj_/dicomfile',
	  'status': 'error',
	  'type': 'file'}]

If we add that exception_traceback into the record, it would not be
displayed to the user in their invocation, e.g:

	$> datalad download-url s3://NDAR_Central_4/submission_XXX/dataset_description.json
	[INFO   ] Downloading 's3://NDAR_Central_4/submission_XXX/dataset_description.json' into '/tmp/'
	INFO:datalad.ui.dialog:Clear progress bars
	download_url(error): /tmp/ (file) [__init__() missing 4 required positional arguments: 'access_key', 'secret_key', 'session', and 'expiration' [nda_aws_token_generator.py:__parse_response:95]]
	INFO:datalad.ui.dialog:Refresh progress bars

but would be visible in cases where we dump entire record (tests?) or
explicitly requested:

	$> datalad -f json_pp download-url s3://NDAR_Central_4/submission_XXX/dataset_description.json
	[INFO   ] Downloading 's3://NDAR_Central_4/submission_XXX/dataset_description.json' into '/tmp/'
	INFO:datalad.ui.dialog:Clear progress bars
	{
	  "action": "download_url",
	  "exception_traceback": "[download_url.py:__call__:178,providers.py:download:478,base.py:download:503,base.py:access:159,s3.py:_establish_session:210,s3.py:authenticate:92,credentials.py:__call__:287,credentials.py:_nda_adapter:296,nda_aws_token_generator.py:generate_token:34,nda_aws_token_generator.py:__make_request:82,nda_aws_token_generator.py:__parse_response:95]",
	  "path": "/tmp/",
	  "status": "error",
	  "type": "file"
	}
	INFO:datalad.ui.dialog:Refresh progress bars

thus making it easier to troubleshoot.