BF(DIRTY): ensure that we never allow for gc to run detached
Otherwise subsequent  git  command invocation might fail to find
objects etc, as Adina has found in her example on her laptop:

	#!/usr/bin/sh

	set -e -x

	datalad create ima
	cd ima
	datalad download-url \
		 --archive \
		 --message "Download Imagenette dataset" \
		 'https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz'

	cd ../
	datalad create -c text2git -c yoda ml
	cd ml

	mkdir -p data
	datalad clone -d . ../ima data/raw

leading to errors like

	CommandError: 'git clone --progress ../ima /tmp/ml/data/raw' failed with exitcode 128 [err: 'Cloning into '/tmp/ml/data/raw'...
	fatal: failed to copy file to '/tmp/ml/data/raw/.git/objects/2f/f2467efde6304a84a1a2f52eee3f5a5fa5448d': No such file or directory']]

We have numerous spots were we invoke git without some centralization and
common place is the GitWitlessRunner.  That is why in this DIRTY hack I just
overloaded `run` to ensure us passing that configuration setting to git, since
AFAIK it cannot be passed through env var (or am I wrong?)

Since we would be always passing it, I have effectively "disabled"
background gc in GitRepo.gc used in a single script among tools