BF(TST): also set encoding (to None) in the monkey patched StringIO
Otherwise datalad/support/tests/test_annexrepo.py:test_ro_operations fails
since

  File "/home/travis/build/datalad/datalad/datalad/support/tests/test_annexrepo.py", line 2610, in test_ro_operations
    Ls.__call__(repo2.path, all_=True, long_=True)
  File "/home/travis/build/datalad/datalad/datalad/interface/ls.py", line 149, in __call__
    return _ls_json(loc, json=json, **kw) if json else _ls_dataset(loc, **kw)
  File "/home/travis/build/datalad/datalad/datalad/interface/ls.py", line 498, in _ls_dataset
    formatter = LsFormatter()
  File "/home/travis/build/datalad/datalad/datalad/interface/ls.py", line 388, in __init__
    if sys.stdout.encoding is None:
AttributeError: StringIO instance has no attribute encoding