BF: get_content_info: Work around ls-files bug in old Git versions
`git ls-files -o .git/` incorrectly traverses the .git/ directory
before Git 2.25, specifically b9670c1f5e (dir: fix checks on common
prefix directory, 2019-12-19).  To get consistent behavior with older
versions of Git that we support, filter out ls-files results that
start with ".git/".

This change fixes a recent test_copy_file_prevent_dotgit_placement()
failure on master with Git versions before 2.25.  Despite the .git/
checks, there are cases where a file can get copied to a destination
in .git/.  Due to the `ls-files -o` bug above, save() considers
.git/config as a file of interest, leading to `git annex add` being
called with a file in .git/.  The `git annex add` call fails,
presumably due to the ls-files bug also affecting it internal logic:

  {"command":"add","note":"non-large file; adding content to git repository",
   "success":true,"input":[".git/config"],"error-messages":[],"file":".git/config"}
  error: invalid path '.git/config'
  error: unable to add '.git/config' to index
  fatal: adding files failed
  git-annex: user error
  (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","add","--"]
   exited 123)

The reason we now see these failures on master is that, with the
switch to _call_annex_records() in 46d78a8353 (RF: Replace all usage
of AnnexRepo._run_annex_command_json(), 2020-11-18), a CommandError is
raised for the `git annex add` call.  Before _run_annex_command_json()
returned the successful looking record above.

With a Git after 2.25, this failure doesn't happen because `ls-files
-o` doesn't report the file, and so the save() call doesn't result in
the .git/ file being passed to `git annex add`.  Even if it were
passed to `git annex add`, git-annex would ignore it rather than fail.

Fixes #5248.