BF: archives.decompress_file: Don't fail on zip files (PY3)
Decompressing a zip under Python 3 fails with

  patoolib.util.PatoolError: error extracting b'/tmp/blah.zip':
  'bytes' object has no attribute 'seek'

Note that this error is happening in zip-file specific
code (py_zipfile.py:extract_zip).  Unlike tar files, zip files don't
get decompressed via a call to the monkey-patched runner (which, at
least in boring cases, handles a command list that is a mix of byte
and unicode strings).

Confusingly, issue gh-2580 and the fix (gh-2586, 7c8500a4a) show
add_archive_content calls on a zip file that don't trigger this error.
But trying on the same zip file, I see the above error.  My patool
version matches the one reported in gh-2586, so perhaps it depends on
the specific Python 3 version (3.6.4 there, 3.5.3 on my end).  Anyway,
the new test will indicate whether the fix here causes issues with
other Python 3 versions that we use on Travis.

The most minimal fix would be to add

    archive = assure_unicode(archive)

below `if not PY2`.  However, I don't understand why we shouldn't
unconditionally call assure_unicode.  Unfortunately, the message of
the commit that added the assure_bytes calls (586a3fd8c) is short on
details.  Let's unconditionally assure_unicode unless Travis tells us
otherwise.

Fixes #2695.