BF: config - become consistent with git in treating key without any value as True
In our case these changes will

- result in `None` being the value
- `getbool` returning `True` (really adhoc, not part of any2bool since
  makes little sense generally)

Without this fix our code would simply crash while reading a legit (to
git) .git/config with

      File "/home/yoh/proj/datalad/datalad-maint/datalad/config.py", line 301, in reload
        log_stderr=True
      File "/home/yoh/proj/datalad/datalad-maint/datalad/config.py", line 96, in _parse_gitconfig_dump
        kv_match = cfg_kv_regex.match(line)
    AttributeError: 'NoneType' object has no attribute 'groups'

A little more on this messy issue of boolean values could be found
in a recent discussion on git-annex:

https://git-annex.branchable.com/bugs/does_not_understand___34__yes__34___as_boolean_true_value_for_autoenable/