BF: With 10.20220128 and up, parse git-annex find output for non-existing files
A recent git-annex release changed the result of running 'git annex
find' on non-existing paths from an error to exit-code 0 with a more
informative hint:

$ git annex find --copies 0 --json --json-error-messages qwdqwd csdc
error: pathspec 'qwdqwd' did not match any file(s) known to git
error: pathspec 'csdc' did not match any file(s) known to git
Did you forget to 'git add'?

Previously, in order to determine whether non-existent paths were
queried, datalad relied on catching and parsing the command error.

CommandError: 'git -c diff.ignoreSubmodules=none annex find --copies 0
--json --json-error-messages -c annex.dotfiles=true -- nothere' failed
with exitcode 1
[info keys: stdout_json] [err: 'git-annex: nothere not found
find: 1 failed']

Because such a CommandError is not thrown anymore, this change parses
the stderror of the output depending on the git-annex version, looking
for files reported as not existing in a similar way to how the command
error is parsed, and assembled an output dictionary to report those
files as missing.