BF(py2): runner: Avoid encoding error when env has unicode
Under Python 2, convert the current working directory value to bytes
because that may be added to env, which can lead to an encoding error

  py2> subprocess.call(":", env={"VAR": u"β"})
  [...]
  raise child_exception
  UnicodeEncodeError: 'ascii' codec can't encode character [...]