ENH: Prefer structured over rendered info
CommandError(msg=) was abused to obfuscate information and
cwd etc. Not these are dedicated properties, and a comprehensive
str representation is rendered at the latest possible stage,
avoiding intermediate overhead.

Turns

```
% datalad create blowup --bare
[INFO   ] Creating a new annex repo at /tmp/blowup
CommandError: command '['git', '-c', 'annex.largefiles=nothing', 'add', '--dry-run', '-N', '--ignore-missing', '--verbose', '--', '.gitattributes']' failed with exitcode 128
Failed to run ['git', '-c', 'annex.largefiles=nothing', 'add', '--dry-run', '-N', '--ignore-missing', '--verbose', '--', '.gitattributes'] under '/tmp/blowup'. Exit code=128. out= err=fatal: this operation must be run in a work tree

stdout=
stderr=fatal: this operation must be run in a work tree

fatal: this operation must be run in a work tree
```

into

```
% datalad create blowup --bare
[INFO   ] Creating a new annex repo at /tmp/blowup
CommandError: 'git -c annex.largefiles=nothing add --dry-run -N --ignore-missing --verbose -- .gitattributes' failed with exitcode 128 under /tmp/blowup
fatal: this operation must be run in a work tree
```