BF: archives.decompress_file: Partially revert 199f092a3
This reverts the decompress_file changes from 199f092a3 and applies
the minimal alternative fix discussed in that commit's message.  This
is in response to failures on the buildbots (all of the Travis runs
passed).  That seems to boil down to a failed git annex get call:

  CommandError: CommandError: command '['git', 'annex', 'get', '--',
  u' "\';a&b&c\u0394\u0419\u05e7\u0645\u0e57\u3042 `| ']' failed with
  exitcode 1

Fixes #2695.