RF: Make SSHConnection.open() errors actionable for callers()
Changes the return value semantics (see inside) and raises
`CommandError` when no ControlMaster can be started. This enables
to act on error on the caller side without causing spurious
warnings.

It turns the output given in gh-3450:

```
% datalad publish --to bareremote --transfer-data all
mih@datalad-test: Permission denied (publickey,password).
[WARNING] Failed to run cmd ['ssh', '-fN', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=15m', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/c5820c82', 'datalad-test']. Exit code=255
| stdout: None
| stderr: None
[ERROR  ] Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)
|   cmdline: /usr/lib/git-annex.linux/git fetch --progress -v bareremote
|   stderr: 'fatal: Could not read from remote repository.
|
| Please make sure you have the correct access rights
| and the repository exists.' [cmd.py:wait:412] (GitCommandError)
```

into a leaning, easier to comprehend

```
% datalad publish --to bareremote --transfer-data all
mih@datalad-test: Permission denied (publickey,password).
CommandError: command '['ssh', '-fN', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=15m', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/c5820c82', 'datalad-test']' failed with exitcode 255
Failed to open SSH connection (could not start ControlMaster process)
```

and thereby fixes gh-3450