BF: do not blow hard in python -O0 mode of operation
This fix is not yet a complete set of changes to be done, but it does
fixes #2461  in that it would not blow on a basic import and otherwise
largely work

Outstanding failures would be:

	======================================================================
	ERROR: datalad.downloaders.tests.test_s3.test_s3_download_basic('s3://datalad.test1/version1.txt', 'nothing', 'version1')
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 591, in newfunc
		return t(*(arg + (filename,)), **kw)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/downloaders/tests/test_http.py", line 239, in check_download_external_url
		downloaded_path = downloader.download(url, path=d)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/downloaders/base.py", line 468, in download
		return self.access(self._download, url, path=path, **kwargs)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/downloaders/base.py", line 141, in access
		used_old_session = self._establish_session(url, allow_old=allow_old_session)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/downloaders/s3.py", line 197, in _establish_session
		self._bucket = self.authenticator.authenticate(bucket_name, self.credential)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/downloaders/s3.py", line 94, in authenticate
		self.bucket = bucket = get_bucket(conn, bucket_name)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/support/s3.py", line 89, in get_bucket
		bucket = conn.get_bucket(bucket_name)
	  File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 506, in get_bucket
		return self.head_bucket(bucket_name, headers=headers)
	  File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 525, in head_bucket
		response = self.make_request('HEAD', bucket_name, headers=headers)
	  File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 668, in make_request
		retry_handler=retry_handler
	  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
		retry_handler=retry_handler)
	  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 944, in _mexe
		response = connection.getresponse()
	  File "/usr/lib/python2.7/dist-packages/vcr/stubs/__init__.py", line 232, in getresponse
		self.cassette.record_mode)
	CannotOverwriteExistingCassetteException: No match for the request (<Request (HEAD) https://s3.amazonaws.com/datalad.test1/>) was found. Can't overwrite existing cassette ('fixtures/vcr_cassettes/test_s3_download_basic.yaml') in your current record mode ('once').

	======================================================================
	ERROR: datalad.interface.tests.test_ls.test_ls_s3
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 817, in newfunc
		return func(*args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 105, in __call__
		function, args, kwargs
	  File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 120, in _execute_function
		return self._handle_function(fn=handle_function)
	  File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 141, in _handle_function
		return fn(cassette)
	  File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 113, in handle_function
		return function(*args, **kwargs)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/tests/test_ls.py", line 47, in test_ls_s3
		res = ls(url)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/ls.py", line 146, in __call__
		**kw)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/ls.py", line 639, in _ls_s3
		_ = urlopen(Request(url))
	  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
		return opener.open(url, data, timeout)
	  File "/usr/lib/python2.7/urllib2.py", line 429, in open
		response = self._open(req, data)
	  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
		'_open', req)
	  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
		result = func(*args)
	  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
		return self.do_open(httplib.HTTPConnection, req)
	  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
		r = h.getresponse(buffering=True)
	  File "/usr/lib/python2.7/dist-packages/vcr/stubs/__init__.py", line 232, in getresponse
		self.cassette.record_mode)
	CannotOverwriteExistingCassetteException: No match for the request (<Request (GET) http://datalad-test0-versioned.s3.amazonaws.com/1version-removed-recreated.txt?versionId=B7cP2PKGRNeRZ7EktWN82UnUaGjb9dh_>) was found. Can't overwrite existing cassette ('fixtures/vcr_cassettes/test_ls_s3.yaml') in your current record mode ('once').

	======================================================================
	ERROR: Failure: TypeError (unsupported operand type(s) for +: 'NoneType' and 'str')
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
		addr.filename, addr.module)
	  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
		return self.importFromDir(dir_path, fqname)
	  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
		mod = load_module(part_fqname, fh, filename, desc)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/test_auto.py", line 37, in <module>
		import nibabel as nib
	  File "/usr/lib/python2.7/dist-packages/nibabel/__init__.py", line 41, in <module>
		from . import nifti1 as ni1
	  File "/usr/lib/python2.7/dist-packages/nibabel/nifti1.py", line 1750, in <module>
		class Nifti1Pair(analyze.AnalyzeImage):
	  File "/usr/lib/python2.7/dist-packages/nibabel/nifti1.py", line 1780, in Nifti1Pair
		<default-sform-qform-codes>` for more details.  '''
	TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

	======================================================================
	ERROR: datalad.tests.test_utils.test_import_module_from_file
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 418, in newfunc
		return t(*(arg + (d,)), **kw)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/test_utils.py", line 1029, in test_import_module_from_file
		import_module_from_file(op.join(topdir, 'dltestm2', 'dlsub1'))
	  File "/home/yoh/proj/datalad/datalad-master/datalad/utils.py", line 1881, in import_module_from_file
		"Failed to import module from %s: %s" % (modpath, exc_str(e)))
	RuntimeError: Failed to import module from /home/yoh/.tmp/datalad_temp_tree_test_import_module_from_filewcjvlE/dltestm2/dlsub1: No module named dls [utils.py:import_module_from_file:1872]

	======================================================================
	FAIL: datalad.downloaders.tests.test_http.test_docstring
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/downloaders/tests/test_http.py", line 76, in test_docstring
		assert_in("\ncredential: Credential", doc)
	AssertionError: '\ncredential: Credential' not found in ''

	======================================================================
	FAIL: datalad.interface.tests.test_add_archive_content.TestAddArchiveOptions.test_add_delete_after_and_drop
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/tests/test_add_archive_content.py", line 426, in test_add_delete_after_and_drop
		self.annex.whereis(key1, key=True, output='full')
	AssertionError: Exception not raised

	======================================================================
	FAIL: datalad.interface.tests.test_utils.test_eval_results_plus_build_doc
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/tests/test_utils.py", line 242, in test_eval_results_plus_build_doc
		assert_in("TestUtil's fake command", doc1)
	AssertionError: "TestUtil's fake command" not found in u'Parameters\n----------\nnumber : str or None\n  It\'s a number.\ndataset : Dataset or None, optional\n  "specify the dataset to update.  If no dataset is given, an attempt\n  is made to identify the dataset based on the input and/or the\n  current working directory. [Default: None]\non_failure : {\'ignore\', \'continue\', \'stop\'}, optional\n  behavior to perform on failure: \'ignore\' any failure is reported,\n  but does not cause an exception; \'continue\' if any failure occurs an\n  exception will be raised at the end, but processing other actions\n  will continue for as long as possible; \'stop\': processing will stop\n  on first failure and an exception is raised. A failure is any result\n  with status \'impossible\' or \'error\'. Raised exception is an\n  IncompleteResultsError that carries the result dictionaries of the\n  failures in its `failed` attribute. [Default: \'continue\']\nproc_post\n  Like `proc_pre`, but procedures are executed after the main command\n  has finished. [Default: None]\nproc_pre\n  DataLad procedure to run prior to the main command. The argument a\n  list of lists with procedure names and optional arguments.\n  Procedures are called in the order their are given in this list. It\n  is important to provide the respective target dataset to run a\n  procedure on as the `dataset` argument of the main command.\n  [Default: None]\nresult_filter : callable or None, optional\n  if given, each to-be-returned status dictionary is passed to this\n  callable, and is only returned if the callable\'s return value does\n  not evaluate to False or a ValueError exception is raised. If the\n  given callable supports `**kwargs` it will additionally be passed\n  the keyword arguments of the original API call. [Default: None]\nresult_renderer : {\'default\', \'json\', \'json_pp\', \'tailored\'} or None, optional\n  format of return value rendering on stdout. [Default: None]\nresult_xfm : {\'paths\', \'relpaths\', \'datasets\', \'successdatasets-or-none\', \'metadata\'} or callable or None, optional\n  if given, each to-be-returned result status dictionary is passed to\n  this callable, and its return value becomes the result instead. This\n  is different from `result_filter`, as it can perform arbitrary\n  transformation of the result value. This is mostly useful for top-\n  level command invocations that need to provide the results in a\n  particular format. Instead of a callable, a label for a pre-crafted\n  result transformation can be given. [Default: None]\nreturn_type : {\'generator\', \'list\', \'item-or-list\'}, optional\n  return value behavior switch. If \'item-or-list\' a single value is\n  returned instead of a one-item return value list, or a list in case\n  of multiple return values. `None` is return in case of an empty\n  list. [Default: \'list\']\n'
	-------------------- >> begin captured logging << --------------------
	datalad.interface.utils: DEBUG: Determined class of decorated function: <class 'datalad.interface.tests.test_utils.TestUtils'>
	--------------------- >> end captured logging << ---------------------

	======================================================================
	FAIL: datalad.support.tests.test_external_versions.test_custom_versions
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/support/tests/test_external_versions.py", line 133, in test_custom_versions
		assert_equal(set(ev.versions.keys()), {'cmd:annex'})
	AssertionError: Items in the second set but not the first:
	'cmd:annex'

	======================================================================
	FAIL: datalad.support.tests.test_external_versions.test_external_versions_rogue_module
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 591, in newfunc
		return t(*(arg + (filename,)), **kw)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/support/tests/test_external_versions.py", line 127, in test_external_versions_rogue_module
		assert_in('pickaboo', cml.out)
	AssertionError: 'pickaboo' not found in ''

	======================================================================
	FAIL: datalad.support.tests.test_gitrepo.test_split_remote_branch
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/support/tests/test_gitrepo.py", line 869, in test_split_remote_branch
		assert_raises(AssertionError, split_remote_branch, "NoSlashesAtAll")
	AssertionError: AssertionError not raised

	======================================================================
	FAIL: datalad.support.tests.test_locking.test_lock_if_check_fails
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 591, in newfunc
		return t(*(arg + (filename,)), **kw)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/support/tests/test_locking.py", line 81, in test_lock_if_check_fails
		ok_(q.get())
	AssertionError: None
	-------------------- >> begin captured logging << --------------------
	fasteners.process_lock: Level 5: Acquired file lock `/home/yoh/.tmp/datalad_temp_test_lock_if_check_failsapEa5w.lck` after waiting 0.000s [1 attempts were required]
	fasteners.process_lock: Level 5: Unlocked and closed file lock open on `/home/yoh/.tmp/datalad_temp_test_lock_if_check_failsapEa5w.lck`
	fasteners.process_lock: Level 5: Acquired file lock `/home/yoh/.tmp/datalad_temp_test_lock_if_check_failsapEa5w.get-lck` after waiting 0.000s [1 attempts were required]
	fasteners.process_lock: Level 5: Unlocked and closed file lock open on `/home/yoh/.tmp/datalad_temp_test_lock_if_check_failsapEa5w.get-lck`
	fasteners.process_lock: Level 5: Acquired file lock `/home/yoh/.tmp/datalad_temp_test_lock_if_check_failsapEa5w.lck` after waiting 0.000s [1 attempts were required]
	fasteners.process_lock: Level 5: Unlocked and closed file lock open on `/home/yoh/.tmp/datalad_temp_test_lock_if_check_failsapEa5w.lck`
	--------------------- >> end captured logging << ---------------------

	======================================================================
	FAIL: datalad.ui.tests.test_base.test_tests_ui
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/ui/tests/test_base.py", line 71, in test_tests_ui
		assert_equal(ui.question("text"), 'a')
	AssertionError: AssertionError not raised

	======================================================================
	FAIL: datalad.ui.tests.test_base.test_with_testsui
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/ui/tests/test_base.py", line 100, in test_with_testsui
		assert_raises(AssertionError, nothing, 1, k=2)
	AssertionError: AssertionError not raised

	======================================================================
	FAIL: datalad.tests.test_dochelpers.test_borrow_kwargs
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/test_dochelpers.py", line 119, in test_borrow_kwargs
		assert_true('B.met1 doc' in B.met1.__doc__)
	AssertionError: False is not true

	----------------------------------------------------------------------
	Ran 850 tests in 1671.522s

	FAILED (SKIP=52, errors=4, failures=10)
	python -OO -m nose -s -v datalad 2>&1  945.75s user 702.32s system 98% cpu 27:54.59 total