Boost python to 3.8 during extensions testing to please datalad-next
Currently testing of datalad-next is failing due to

	AttributeError: module 'gzip' has no attribute 'BadGzipFile'

and that one was added in 3.8.  I have not researched how come appveyor with
3.7 testing in datalad-next is not running into this.  As 3.7 is about to EOL,
I think it is ok to start testing downstream extensions with the next 3.8.