BF: Report info from annex JSON error message in CommandError
When a `CommandError` bubbles up to the main entrypoint it is rendered
differently than anywhere else (calls `to_str()` with
`include_output=False`. This is done to be able to write the
`stdout|err` output of a failed command to the proper channels. However,
this also caused all information extraction from JSON records to be
disabled.

This change, makes sure that JSON records are processed even in this
case. It also RFs the exception rendering code to make it less
repr()-like.

From:

```
CommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch -z --to expdir --fast --json --json-error-messages --json-progress -c annex.dotfiles=true' failed with exitcode 1 under /tmp/testds
git-annex: copy: 2 failed
```

To:

```
CommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch -z --to expdir --fast --json --json-error-messages --json-progress -c annex.dotfiles=true' failed with exitcode 1 under /tmp/testds [info keys: stdout_json]
> to expdir...
  remote is configured with exporttree=yes; use `git-annex export` to store content on it
  This could have failed because --fast is enabled. [2 times]
git-annex: copy: 2 failed
```

Fixes datalad/datalad#5807