RF: Bypass URL size check in download-url
Not fully confident here. We already have the file at this point,
so no info is lost. Moreover, without this change, the original
use case from https://github.com/datalad/datalad/issues/2849
leads to:

  download_url(ok): /tmp/this/open-iconic-bootstrap.min.css (file)
  add(ok): open-iconic-bootstrap.min.css (file)
  save(ok): . (dataset)
  [WARNING] Running addurl resulted in stderr output: git-annex: addurl: 1 failed

  CommandError: command 'addurl'
  Error, annex reported failure for addurl (url='https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css'): {'command': 'addurl', 'success': False, 'error-messages': ['  while adding a new url to an already annexed file, url does not have expected file size (use --relaxed to bypass this check) https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css'], 'file': 'open-iconic-bootstrap.min.css'}

So any URL where the server doesn't provide a size would fail to work
with `download-url` by default. I think this is too strict behavior,
hence disabling that check.