RF: get_modules_ - avoid O(N^2) if paths provided via use of get_limited_paths
Redone #6974 and #7211 which attempted to reuse get_parent_paths with tune ups
-- was not sufficient since need to have a bit ad-hoc limiting by the path
WITHIN submodule to select that submodule (which would not work for plain directory).

Overall -- now that #7189 has finished the RFing to avoid some slow
operations at the cost of making some use cases slower, this should resolve it
back to avoid any slow operation.

#6974 commits avoided a hypothetical infinite recursion (my code analysis
says it was not possible, see #6941 (comment)) and performance issues by
introducing similar logic directly in the code of get_modules_.

get_limited_paths relies on sorting of the paths, should be O(N*log(N)) but
generally likely faster since likely to get them sorted to start with.

Timing this branch:

    ❯ datalad --version; (builtin cd /home/yoh/datalad/hcp-openaccess; /bin/time python -c "from datalad.support.gitrepo import *; from glob import glob; print('\n'.join(map(str,GitRepo('.').get_submodules_(glob('HCP1200/*')))))" | wc -l; )
    datalad 0.17.9+185.gd236b5a6d
    0.79user 0.14system 0:00.89elapsed 105%CPU (0avgtext+0avgdata 28896maxresident)k
    824inputs+0outputs (1major+8149minor)pagefaults 0swaps
    1113

and master

    ❯ datalad --version; (builtin cd /home/yoh/datalad/hcp-openaccess; /bin/time python -c "from datalad.support.gitrepo import *; from glob import glob; print('\n'.join(map(str,GitRepo('.').get_submodules_(glob('HCP1200/*')))))" | wc -l; )
    datalad 0.17.9+183.g34a28a622
    4.29user 0.11system 0:04.39elapsed 100%CPU (0avgtext+0avgdata 29092maxresident)k
    0inputs+0outputs (0major+8226minor)pagefaults 0swaps
    1113

and maint

    ❯ datalad --version; (builtin cd /home/yoh/datalad/hcp-openaccess; /bin/time python -c "from datalad.support.gitrepo import *; from glob import glob; print('\n'.join(map(str,GitRepo('.').get_submodules_(glob('HCP1200/*')))))" | wc -l; )
    datalad 0.17.9+82.g405ece550
    0.97user 0.12system 0:01.05elapsed 104%CPU (0avgtext+0avgdata 30248maxresident)k
    0inputs+0outputs (0major+8633minor)pagefaults 0swaps
    1113

so we are no worse (if not better) than maint and definetely gain over master
for such use cases of N submodules/N paths given. And for a single path we might even be not only faster but fixing some bug in maint:

	❯ datalad --version; (builtin cd /home/yoh/datalad/hcp-openaccess; /bin/time python -c "from datalad.support.gitrepo import *; from glob import glob; print('\n'.join(map(str,GitRepo('.').get_submodules_(glob('HCP1200/*')[1]))))" | wc -l; )
	datalad 0.17.9+185.g8b21bfceb
	0.65user 0.11system 0:00.75elapsed 101%CPU (0avgtext+0avgdata 28040maxresident)k
	104inputs+0outputs (0major+7652minor)pagefaults 0swaps
	1

	❯ git co master
	Switched to branch 'master'
	Your branch is up to date with 'origin/master'.

	❯ datalad --version; (builtin cd /home/yoh/datalad/hcp-openaccess; /bin/time python -c "from datalad.support.gitrepo import *; from glob import glob; print('\n'.join(map(str,GitRepo('.').get_submodules_(glob('HCP1200/*')[1]))))" | wc -l; )
	datalad 0.17.9+183.g34a28a622
	0.75user 0.10system 0:00.83elapsed 102%CPU (0avgtext+0avgdata 28816maxresident)k
	0inputs+0outputs (0major+8203minor)pagefaults 0swaps
	1113

	❯ git co maint
	Switched to branch 'maint'
	Your branch is up to date with 'origin/maint'.

	❯ datalad --version; (builtin cd /home/yoh/datalad/hcp-openaccess; /bin/time python -c "from datalad.support.gitrepo import *; from glob import glob; print('\n'.join(map(str,GitRepo('.').get_submodules_(glob('HCP1200/*')[1]))))" | wc -l; )
	datalad 0.17.9+82.g405ece550
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 2388, in get_submodules_
		for path, props in self.get_content_info(
	  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 2769, in get_content_info
		posix_paths = get_parent_paths(posix_paths, submodules)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/support/path.py", line 191, in get_parent_paths
		_get_parent_paths_check(path, sep, asep)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/support/path.py", line 213, in _get_parent_paths_check
		raise ValueError("Expected relative within directory paths, got %r" % path)
	ValueError: Expected relative within directory paths, got '/'
	Command exited with non-zero status 1
	0.39user 0.04system 0:00.43elapsed 101%CPU (0avgtext+0avgdata 29832maxresident)k
	0inputs+0outputs (0major+8107minor)pagefaults 0swaps
	0