RF+BF: make cookies db access/closing more robust
While running tests under some conda environment, there were errors while closing
cookies DB. Could not reproduce in the native Debian environment with similarishish
Python.  With these changes, cookies_db is a property so it gets properly
loadded before setting any value. And also we catch exceptions upon
close and report them as a warning if there were some cookies to store.

Unfortunately Python in conda env still prints directly the entire traceback, and
on Debian some error message even before throwing the exception so you could see something like

    $> DATALAD_LOG_LEVEL=INFO python -m nose -s -v datalad/support/tests/test_cookies.py
    datalad.support.tests.test_cookies.test_no_blows ... [WARNING] Failed to save possibly updated 1 cookies (best): [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_test_no_blows1_rmfcb2/mycookies.dat' [dumb.py:_setval:178]
    Exception ignored in: <function _Database.close at 0x7f1fe46872f0>
    Traceback (most recent call last):
      File "/home/yoh/anaconda-2018.12-3.7/envs/test-gitpython/lib/python3.7/dbm/dumb.py", line 284, in close
        self._commit()
      File "/home/yoh/anaconda-2018.12-3.7/envs/test-gitpython/lib/python3.7/dbm/dumb.py", line 135, in _commit
        with self._io.open(self._dirfile, 'w', encoding="Latin-1") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_test_no_blows1_rmfcb2/mycookies.dir'
    ok