ENH: log up to 100 of last lines in stderr (if log outputs) for batched processes
I am chasing some bug in datalad/git-annex where batched addurls
eventually crashes with

	datalad.cmd     [DEBUG  ] Closing stdin of <subprocess.Popen object at 0x7fa14a7cb940> and waiting process to finish
	datalad.utils   [WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #1. Sleeping 1.000000 and retrying
	datalad.utils   [WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #2. Sleeping 1.000000 and retrying
	datalad.cmd     [WARNING] Batched process <subprocess.Popen object at 0x7fa14a7cb940> did not finish, abandoning it without killing it
	Traceback (most recent call last):
	  File "datalad-nda/scripts/datalad-nda", line 416, in <module>
		main()
	  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
		return self.main(*args, **kwargs)
	  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
		rv = self.invoke(ctx)
	  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
		return callback(*args, **kwargs)
	  File "datalad-nda/scripts/datalad-nda", line 236, in add2datalad
		on_failure="stop",
	  File "/mnt/scrap/tmp/abcd/datalad/datalad/distribution/dataset.py", line 503, in apply_func
		return f(**kwargs)
	  File "/mnt/scrap/tmp/abcd/datalad/datalad/interface/utils.py", line 481, in eval_func
		return return_func(generator_func)(*args, **kwargs)
	  File "/mnt/scrap/tmp/abcd/datalad/datalad/interface/utils.py", line 469, in return_func
		results = list(results)
	  File "/mnt/scrap/tmp/abcd/datalad/datalad/interface/utils.py", line 456, in generator_func
		msg="Command did not complete successfully")
	datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
	[{'action': 'addurls',
	  'message': "AnnexBatchCommandError: 'addurl' [Error, annex reported failure "
				 'for addurl '
				 "(url='s3://NDAR_Central_2/submission_23229/derivatives/abcd-hcp-pipeline/sub-XXX/ses-baselineYear1Arm1/img/DVARS_and_FD_task-SST01.png'): "
				 "{'command': 'addurl', 'success': False, 'error-messages': ['  "
				 "unable to use special remote due to protocol error'], 'file': "
				 "'sub-XXX/ses-baselineYear1Arm1/img/DVARS_and_FD_task-SST01.png'}] "
				 '[annexrepo.py:add_url_to_file:1879]',
	  'path': '/mnt/scrap/tmp/abcd/testds-fast-full2/derivatives/abcd-hcp-pipeline/sub-XXX/ses-baselineYear1Arm1/img/DVARS_and_FD_task-SST01.png',
	  'status': 'error',
	  'type': 'file'}]

	> /mnt/scrap/tmp/abcd/datalad/datalad/interface/utils.py(456)generator_func()
	-> msg="Command did not complete successfully")

I have no clue what is going on and since it is a sandwich of
datalad/git-annex/git-annex-remote-datalad-archives here -- it is hard to
impossible to see what is happening.  Logging last lines from stderr might give
a clue if would include relevant log lines from special remote log etc.