TST: Disable tests on Windows due to ORA issue (initremote fails)
```
======================================================================
ERROR: datalad.distributed.tests.test_create_sibling_ria.test_storage_only
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\mih\code\datalad\datalad\distributed\tests\test_create_sibling_ria.py", line 195, in test_storage_only
    res = ds.create_sibling_ria(store_url, "datastore", storage_sibling='only')
...
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'create-sibling-ria',
  'message': 'initremote failed.\n'
             'stdout: initremote datastore \n'
             'failed\n'
             '\n'
             'stderr: git-annex: Cannot determine special remote name, got: '
             "''\r\n"
             'git-annex: initremote: 1 failed\n',
  'path': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_89p9vbry',
  'status': 'error',
  'type': 'dataset'}]
```