BF(py2): create: Fix Unicode error with non-ascii paths
Under Python 2, GitPython expects a byte string here:

    File "[...]/lib/python2.7/site-packages/git/repo/base.py", line 126, in __init__
        epath = str(epath)
    UnicodeEncodeError: 'ascii' codec can't encode characters in
    position 63-68: ordinal not in range(128)

Note that master's local/create.py also fails with a different Unicode
error under Python 2.  That will be fixed in a separate series.