RF: config - where->scope and handle "dataset" -> "branch"
Incomplete.  Upon a quick test to see the warning, saw an error:

	$> python -Wonce -c 'from datalad import cfg ; cfg.unset("datalad.clone.url-substitute.osf", where="dataset")'
	<frozen importlib._bootstrap_external>:587: ResourceWarning: unclosed file <_io.FileIO name=3 mode='rb' closefd=True>
	ResourceWarning: Enable tracemalloc to get the object allocation traceback
	<frozen importlib._bootstrap_external>:587: ResourceWarning: unclosed file <_io.FileIO name=5 mode='rb' closefd=True>
	ResourceWarning: Enable tracemalloc to get the object allocation traceback
	/home/yoh/proj/datalad/datalad-master/datalad/config.py:101: DeprecationWarning: 'where="dataset"' is being deprecated as of 0.15. Use 'scope="branch"' instead
	  warnings.warn("'where=\"dataset\"' is being deprecated as of 0.15. Use 'scope=\"branch\"' instead",
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 108, in wrapper
		return func(*args, **kwargs)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 984, in unset
		self._run(['--unset-all', var], scope=scope, reload=reload)
	  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 818, in _run
		args = self._get_location_args(scope) + args
	  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 855, in _get_location_args
		raise ValueError(
	ValueError: ConfigManager cannot store configuration to dataset, none specified