BF: exceptions: Restore CLI rendering of CommandError subclasses
09d3fd8ed0 (ENH: Prefer structured over rendered info, 2020-02-16,
gh-4157) switched datalad.cmdline.main over to using to_str() for
rendering a caught CommandError.  None of the CommandError subclasses
have a to_str() method, though, so the value returned by
CommandError.to_str() is displayed rather than the value returned by
the child's __str__() method.

For example, now an OutOfSpaceError is shown as "OutOfSpaceError:  "
rather than "OutOfSpaceError:  needs N more".  Likewise, calling
`datalad get --source=DO-NOT-EXIST` no longer shows the remote name,
just

    RemoteNotAvailableError: 'annex get'

Convert the __str__() methods of all subclasses to to_str().  The
message above becomes

    Remote 'DO-NOT-EXIST' is not available. Command failed:
    RemoteNotAvailableError: 'annex get'

This commit just intends to restore the displayed information that was
lost with 09d3fd8ed0.  However, the rendering of these CommandError
subclasses could arguably be improved (e.g., the "Command failed:
RemoteNotAvailableError: 'annex get'" stacking is confusing and could
probably be dropped altogether).