BF(TST): provide 2nd remtoe on a different URL
since otherwise we can run into indigestion by git-annex such as

	datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex initremote fresh-sr type=git location=http://127.0.0.1:38045/.git autoenable=true -c annex.dotfiles=true' failed with exitcode 1 under /home/yoh/.tmp/datalad_temp_test_as_common_datasource49kq5qqu [out: 'initremote fresh-sr
	failed'] [err: 'git-annex: found multiple git remotes with specified location initremote: 1 failed']