ENH(TST): test completion provided by argcomplete helper
ATM results at following traceback at the end of the tests since argcomplete
uses fd 9 for its debug output, and I guess something/it fails to close
it.  I don't think it is any kind of a show stopper but someone might want
to dig deeper and make it so it doesn't happen:

	Exception ignored in: <Finalize object, dead>
	Traceback (most recent call last):
	  File "/usr/lib/python3.9/multiprocessing/util.py", line 224, in __call__
		res = self._callback(*self._args, **self._kwargs)
	  File "/usr/lib/python3.9/multiprocessing/util.py", line 464, in close_fds
		os.close(fd)
	OSError: [Errno 9] Bad file descriptor