DOC: do not call build_schema
Follow up to https://github.com/datalad/datalad/pull/7014
which removed all metadata handling.  Without this change we get

    ❯ make -C docs html

    make: Entering directory '/home/yoh/proj/datalad/datalad-maint/docs'
    DATALAD_SPHINX_RUN=1 sphinx-build -b html -d build/doctrees  -W source build/html
    Running Sphinx v6.1.3
    running build_manpage
    running build_cfginfo
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: invalid command 'build_schema'
    ... proceeding normally

without crashing so we missed that