BF: add pytest into deps for typing since needed
Overcomes

    error: Cannot find implementation or library stub for module named "pytest"

and I do not think there is types-pytest