BF(TST): cancel futures in reverse order
While running tests while being in zoom (or jitsi) meeting showed following
failure:

	(git)lena:~datalad/datalad-maint[enh-iter-progress]git
	$> DATALAD_LOG_LEVEL=INFO DATALAD_LOG_TRACEBACK=1 python -m nose -s -v datalad/support/tests/test_parallel.py:test_gracefull_death
	datalad.support.tests.test_parallel.test_gracefull_death ... [WARNING] ...>log:209  Received an exception ValueError() [test_parallel.py:faulty_consumer:157].
	| Canceling not-yet running jobs and waiting for completion of running.
	| You can force earlier forceful exit by Ctrl-C.
	[INFO   ] ...>log:209  Canceled 942 out of 998 jobs. 8 left running.
	[WARNING] ...>log:209  Received an exception ValueError() [test_parallel.py:producer:172].
	| Canceling not-yet running jobs and waiting for completion of running.
	| You can force earlier forceful exit by Ctrl-C.
	[INFO   ] ...>log:209  Canceled 2 out of 8 jobs. 2 left running.
	FAIL
	Versions: annexremote=1.4.3 appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20200908+git175-g95d02d6e2-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.28.0 cmd:system-ssh=8.1p1 exifread=2.1.2 git=3.1.0 gitdb=4.0.2 humanize=2.3.0 iso8601=0.1.12 keyring=18.0.1 keyrings.alt=3.4.0 msgpack=0.6.2 mutagen=1.40.0 requests=2.23.0 scrapy=1.7.3 wrapt=1.11.2
	Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
	Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
	Environment: PATH='/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=master'"

	======================================================================
	FAIL: datalad.support.tests.test_parallel.test_gracefull_death
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/home/yoh/proj/datalad/datalad-maint/datalad/tests/utils.py", line 257, in _wrap_skip_if
		return func(*args, **kwargs)
	  File "/home/yoh/proj/datalad/datalad-maint/datalad/support/tests/test_parallel.py", line 203, in test_gracefull_death
		assert_equal(consumed, list(range(len(consumed))))
	AssertionError: Lists differ: [0, 1, 2, 3, 4, 5, 470] != [0, 1, 2, 3, 4, 5, 6]

	First differing element 6:
	470
	6

	- [0, 1, 2, 3, 4, 5, 470]
	?                    ^^^

	+ [0, 1, 2, 3, 4, 5, 6]
	?                    ^

	----------------------------------------------------------------------
	Ran 1 test in 1.422s

	FAILED (failures=1)

so if system busy, executor might still manage to submit some job while they
being canceled.  If it is submitted, better be an earlier one, so we just
cancel jobs in reverse order in the dict.