TST: gitrepo: test_duecredit: Loosen assumption about output string
test_duecredit() expect the output to be entirely empty when duecredit
doesn't emit anything.  At least one time when that isn't the case is
when running with an older Git:

    AssertionError: '[...]/datalad/support/gitrepo.py:978:
    OutdatedExternalDependencyWarning: Your git version (2.13.0) is
    too old, we will not safe-guard against creating a new repository
    under already known to git subdirectory\n
    OutdatedExternalDependencyWarning\n' != ''