ENH(BK): added more benchmarks (for remove) and RFed to tar entire dataset to be reused
to gain some speedups since install is damn slow

But now it leads to that weird failure from git module
ValueError: SHA cd3c4fef67c270d1c719878b064fabd18bfcfeb3 could not be resolved, git returned: 'cd3c4fef67c270d1c719878b064fabd18bfcfeb3 missing'
so committing to record the occasion

got there by running
asv run --python=2.7 --dry-run -v --bench .*SuperdatasetsOperationsSuite..* 0.5.x^..0.5.x
in this dirty tree