BF: define var (to None) before it might be assigned
Ran into

   UnboundLocalError: local variable ver referenced before assignment

although unclear how/why now since prior run (with a little bit different way to it)
did succeed for that matrix run with LC_ALL set to ru_RU.UTF-8